#!/bin/bash
# Compute KL(π_n || π_{n-1}) for each consecutive iteration pair.
#
# Prerequisites: inference_align.sh must have been run so that
#   {INFER_RES_BASE}/{ALIGN_MODEL_DIR}/ckpt{n}/test.json exists for all n.
#
# Usage:
#   bash compute_kl_iters.sh <gpu_ids> <align_model_dir> <sft_model_path> <infer_res_base> <num_iters> [max_length] [batch_size]
#
# Arguments:
#   gpu_ids        e.g. 0,1,2,3,4,5,6,7
#   align_model_dir  path to the iterative training checkpoints dir
#                    e.g. models/qwen2.5-7b_hh/align_online_pp-dpo-rw_nc2
#   sft_model_path   path to the SFT (iter-0) model
#                    e.g. models/qwen2.5-7b_hh/sft
#   infer_res_base   base dir for inference results
#                    e.g. exp/hh_qwen7b_exp/data/hh_infer_res
#   num_iters        number of iterations (e.g. 5)
#   max_length       max sequence length (default: 512)
#   batch_size       batch size for logprob computation (default: 16)
#
# Example — qwen2.5-7b PRPO:
#   bash compute_kl_iters.sh 0,1,2,3,4,5,6,7 \
#       models/qwen2.5-7b_hh/align_online_pp-dpo-rw_nc2 \
#       models/qwen2.5-7b_hh/sft \
#       exp/hh_qwen7b_exp/data/hh_infer_res \
#       5
#
# Example — qwen2.5-3b PRPO:
#   bash compute_kl_iters.sh 0,1,2,3 \
#       models/qwen2.5-3b_hh/align_online_pp-dpo-rw_nc2 \
#       models/qwen2.5-3b_hh/sft \
#       exp/hh_qwen3b_exp/data/hh_infer_res \
#       5
#
# Example — qwen2.5-14b PRPO:
#   bash compute_kl_iters.sh 0,1,2,3,4,5,6,7 \
#       models/qwen2.5-14b_hh/align_online_pp-dpo-rw_nc2 \
#       models/qwen2.5-14b_hh/sft \
#       exp/hh_qwen14b_exp/data/hh_infer_res \
#       5

set -e

GPU_IDS=$1
ALIGN_MODEL_DIR=$2
SFT_MODEL=$3
INFER_RES_BASE=$4
NUM_ITERS=${5:-5}
MAX_LENGTH=${6:-512}
BATCH_SIZE=${7:-16}

KL_OUTPUT_DIR="kl_results/$(basename $ALIGN_MODEL_DIR)"
mkdir -p "$KL_OUTPUT_DIR"

echo "=== KL divergence computation ==="
echo "  Model dir  : $ALIGN_MODEL_DIR"
echo "  SFT model  : $SFT_MODEL"
echo "  Infer res  : $INFER_RES_BASE"
echo "  Iterations : $NUM_ITERS"
echo "  Output dir : $KL_OUTPUT_DIR"
echo ""

run_calc_logprobs() {
    local model_path=$1
    local data_path=$2

    deepspeed --include "localhost:$GPU_IDS" \
              --master_port 12399 \
              src/align_stage/calc_logprobs.py \
              --model_path "$model_path" \
              --data_path  "$data_path" \
              --split test \
              --max_length $MAX_LENGTH \
              --max_new_tokens 200 \
              --batch_size $BATCH_SIZE \
              --dtype fp16 \
              --eval_num 512
}

for n in $(seq 1 $NUM_ITERS); do
    echo "--- Iteration $n ---"

    # data: completions generated by ckpt_n (on-policy for iter n)
    DATA_PATH="${INFER_RES_BASE}/${ALIGN_MODEL_DIR}/ckpt${n}"

    if [ ! -f "${DATA_PATH}/test.json" ]; then
        echo "WARNING: ${DATA_PATH}/test.json not found — skipping iter $n"
        continue
    fi

    CURR_MODEL="${ALIGN_MODEL_DIR}/ckpt${n}"
    if [ $n -eq 1 ]; then
        PREV_MODEL="$SFT_MODEL"
    else
        PREV_MODEL="${ALIGN_MODEL_DIR}/ckpt$((n-1))"
    fi

    CURR_CKPT=$(basename $CURR_MODEL)
    PREV_CKPT=$(basename $PREV_MODEL)

    # compute logprobs under current model (π_n)
    CURR_LOGPROBS="${DATA_PATH}/logprobs_${CURR_CKPT}.json"
    if [ ! -f "$CURR_LOGPROBS" ]; then
        echo "  Computing logprobs under $CURR_CKPT ..."
        run_calc_logprobs "$CURR_MODEL" "$DATA_PATH"
    else
        echo "  Logprobs for $CURR_CKPT already exist, skipping."
    fi

    # compute logprobs under previous model (π_{n-1})
    PREV_LOGPROBS="${DATA_PATH}/logprobs_${PREV_CKPT}.json"
    if [ ! -f "$PREV_LOGPROBS" ]; then
        echo "  Computing logprobs under $PREV_CKPT ..."
        run_calc_logprobs "$PREV_MODEL" "$DATA_PATH"
    else
        echo "  Logprobs for $PREV_CKPT already exist, skipping."
    fi

    # compute KL(π_n || π_{n-1})
    echo "  Computing KL(π_$n || π_$((n-1))) ..."
    KL_VAL=$(python3 src/align_stage/eval_kl.py "$CURR_LOGPROBS" "$PREV_LOGPROBS" 2>/dev/null)
    echo "  KL(iter $n || iter $((n-1))) = $KL_VAL"

    echo "$n $KL_VAL" >> "${KL_OUTPUT_DIR}/kl_values.txt"
done

echo ""
echo "=== KL values written to ${KL_OUTPUT_DIR}/kl_values.txt ==="
cat "${KL_OUTPUT_DIR}/kl_values.txt"
